### ISSUE TITLE
trouble getting agfusion.homo_sapiens.87.db to work with AGFusion

### ISSUE THREAD

**Issue by kac2053** [murphycj/AGFusion#14]
Hi,

I installed AGFusion and I got it to work in your example for DLG1-BRAF for agfusion.mus_musculus.87.db.

However, when I try fusions (ie. RLF-MYCL) using agfusion.homo_sapiens.87.db, I get the following error: 
Traceback (most recent call last):
  File "/home/chuk/bin/miniconda3/bin/agfusion", line 5, in <module>
    cli.main()
  File "/home/chuk/bin/miniconda3/lib/python3.5/site-packages/agfusion/cli.py", line 486, in main
    args=args
  File "/home/chuk/bin/miniconda3/lib/python3.5/site-packages/agfusion/cli.py", line 83, in annotate
    noncanonical=args.noncanonical
  File "/home/chuk/bin/miniconda3/lib/python3.5/site-packages/agfusion/model.py", line 325, in __init__
    protein_databases=protein_databases,
  File "/home/chuk/bin/miniconda3/lib/python3.5/site-packages/agfusion/model.py", line 852, in __init__
    self.predict_effect()
  File "/home/chuk/bin/miniconda3/lib/python3.5/site-packages/agfusion/model.py", line 1550, in predict_effect
    self._fetch_protein()
  File "/home/chuk/bin/miniconda3/lib/python3.5/site-packages/agfusion/model.py", line 1028, in _fetch_protein
    self.cds.seq = self.cds.seq[0:3*(len(self.cds.seq)/3)]
  File "/home/chuk/bin/miniconda3/lib/python3.5/site-packages/Bio/Seq.py", line 240, in __getitem__
    return Seq(self._data[index], self.alphabet)
TypeError: slice indices must be integers or None or have an __index__ method

Please let me know what I can do to try to resolve this issue. Thank you!

**Comment by murphycj** [comment]
Can you give the exact command you're using? I ran the following with no problem (using randomly picked junction coordinates),

```
agfusion annotate -g5 RLF -g3 MYCL -j3 39900938 -j5 40190771 --db agfusion.homo_sapiens.87.db -o test
```

**Comment by kac2053** [comment]
I ran the command you gave above to test. I still get the same error.

**Comment by murphycj** [comment]
What python and biopython versions are you using?

**Comment by kac2053** [comment]
Python 3.5.3
biopython-1.70

**Comment by murphycj** [comment]
Ah, ok it was a minor bug. I patched it. Install again from this GitHub repo and let me know if it works.

**Comment by kac2053** [comment]
How do I uninstall agfusion? Thanks!

**Comment by murphycj** [comment]
```
pip uninstall agfusion
```

**Comment by murphycj** [comment]
I updated the PyPi version. So you can reinstall with:
```
pip install agfusion --upgrade
```

**Comment by kac2053** [comment]
I still get the same error.

Traceback (most recent call last):
  File "/home/chuk/bin/miniconda3/bin/agfusion", line 5, in <module>
    cli.main()
  File "/home/chuk/bin/miniconda3/lib/python3.5/site-packages/agfusion/cli.py", line 486, in main
    args=args
  File "/home/chuk/bin/miniconda3/lib/python3.5/site-packages/agfusion/cli.py", line 83, in annotate
    noncanonical=args.noncanonical
  File "/home/chuk/bin/miniconda3/lib/python3.5/site-packages/agfusion/model.py", line 325, in __init__
    protein_databases=protein_databases,
  File "/home/chuk/bin/miniconda3/lib/python3.5/site-packages/agfusion/model.py", line 852, in __init__
    self.predict_effect()
  File "/home/chuk/bin/miniconda3/lib/python3.5/site-packages/agfusion/model.py", line 1550, in predict_effect
    self._fetch_protein()
  File "/home/chuk/bin/miniconda3/lib/python3.5/site-packages/agfusion/model.py", line 1028, in _fetch_protein
    self.cds.seq = self.cds.seq[0:3*(len(self.cds.seq)/3)]
  File "/home/chuk/bin/miniconda3/lib/python3.5/site-packages/Bio/Seq.py", line 240, in __getitem__
    return Seq(self._data[index], self.alphabet)
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by murphycj** [comment]
Hm, can you verify you have the most recent version installed by running ```agfusion -v```. Should read 0.145

**Comment by kac2053** [comment]
It works. Thanks!!
