### ISSUE TITLE
issue with batch

### ISSUE THREAD

**Issue by kac2053** [murphycj/AGFusion#15]
Hi,

I tried running batch on STAR-Fusion output that contains a known fusion that works with AGFusion "annotate", but the output folder and .stderr were empty, which made it difficult diagnosing the problem.

I also tried running batch on fusion catcher output that contains a known fusion that also works with AGFusion annotate. The output file only contained 2 (out of 15 total) fusions: 1 fusion that was CDS truncated and 1 fusion that was in-frame (out of 4 total in-frame fusions).
The .stderr read the following:

> 2017-08-16 12:11:42,101 - AGFusion - INFO - The TENM4-NARS2 fusion does not produce any protein coding transcripts. No cds.fa file will be written
2017-08-16 12:11:42,101 - AGFusion - INFO - The TENM4-NARS2 fusion does not produce any protein coding transcripts. No proteins.fa file will be written
2017-08-16 12:11:42,236 - AGFusion - INFO - The TENM4-NARS2 fusion does not produce any protein coding transcripts. No cds.fa file will be written
2017-08-16 12:11:42,237 - AGFusion - INFO - The TENM4-NARS2 fusion does not produce any protein coding transcripts. No proteins.fa file will be written
2017-08-16 12:11:42,239 - AGFusion - WARNING - The following output directory already exists! /data/poirier/chuk/fusion_project/AGFusion/AGFusion_all_fusions-filtered/TENM4-79297488_NARS2-78493195
2017-08-16 12:11:42,362 - AGFusion - INFO - The TENM4-NARS2 fusion does not produce any protein coding transcripts. No cds.fa file will be written
2017-08-16 12:11:42,362 - AGFusion - INFO - The TENM4-NARS2 fusion does not produce any protein coding transcripts. No proteins.fa file will be written
2017-08-16 12:11:42,363 - AGFusion - WARNING - The following output directory already exists! /data/poirier/chuk/fusion_project/AGFusion/AGFusion_all_fusions-filtered/TENM4-79297488_NARS2-78478683
2017-08-16 12:11:42,486 - AGFusion - INFO - The TENM4-NARS2 fusion does not produce any protein coding transcripts. No cds.fa file will be written
2017-08-16 12:11:42,486 - AGFusion - INFO - The TENM4-NARS2 fusion does not produce any protein coding transcripts. No proteins.fa file will be written
2017-08-16 12:11:42,611 - AGFusion - INFO - The TENM4-NARS2 fusion does not produce any protein coding transcripts. No cds.fa file will be written
2017-08-16 12:11:42,611 - AGFusion - INFO - The TENM4-NARS2 fusion does not produce any protein coding transcripts. No proteins.fa file will be written
Traceback (most recent call last):
  File "/home/chuk/bin/miniconda3/bin/agfusion", line 5, in <module>
    cli.main()
  File "/home/chuk/bin/miniconda3/lib/python3.5/site-packages/agfusion/cli.py", line 517, in main
    args=args
  File "/home/chuk/bin/miniconda3/lib/python3.5/site-packages/agfusion/cli.py", line 110, in annotate
    exclude=args.exclude_domain
  File "/home/chuk/bin/miniconda3/lib/python3.5/site-packages/agfusion/model.py", line 419, in save_images
    pplot.draw()
  File "/home/chuk/bin/miniconda3/lib/python3.5/site-packages/agfusion/plot.py", line 844, in draw
    self._scale(self.transcript.protein_length)
  File "/home/chuk/bin/miniconda3/lib/python3.5/site-packages/agfusion/plot.py", line 48, in _scale
    if self.scale == -1 or self.scale < seq_length:
TypeError: unorderable types: NoneType() < int()

Commands:

`/home/chuk/bin/miniconda3/bin/agfusion batch \
  --file /data/poirier/chuk/fusion_project/Rudin2012/STAR-Fusion/637122/star-fusion.fusion_candidates.final.abridged \
  -a STAR-Fusion \
  -o /data/poirier/chuk/fusion_project/AGFusion/test \
  --db /home/chuk/bin/miniconda3/bin/agfusion.homo_sapiens.87.db`

`/home/chuk/bin/miniconda3/bin/agfusion batch \
  --file /data/poirier/chuk/fusion_project/George2015/FusionCatcher/_EGAR00001231913_SCLC_Julie_SCLC_RNAseq_S01512/final-list_candidate-fusion-genes.txt \
  -a fusioncatcher \
  -o /data/poirier/chuk/fusion_project/AGFusion/AGFusion_all_fusions-filtered \
  --db /home/chuk/bin/miniconda3/bin/agfusion.homo_sapiens.87.db`

Please let me know what you think may be the problem. Thanks!

**Comment by murphycj** [comment]
I reproduced the issue and pushed a patch (it was a python 3 issue). Please install the latest version (v0.146) and let me know if it fixes the issue for you.

**Comment by kac2053** [comment]
Thank you.

It seems to be working with fusion catcher fusion lists, but I get the same error as before with STAR-Fusion lists.

**Comment by murphycj** [comment]
Hm, you should not get the exact same traceback in the error. Can you print the error message again here?

**Comment by kac2053** [comment]
For STAR-Fusion, the .stderr is empty. There is no error message. The output folder also is empty.

**Comment by murphycj** [comment]
Hm, I tested batch mode on STAR-Fusion output using python 3 and get no problems. Would you mind sending me a small portion of your file (e.g. a couple fusions) so that I may test it out?

**Comment by murphycj** [comment]
The issue turned out to be combination of python 3 and AGFusion not properly checking command line input. Fixed.
