### ISSUE TITLE
STAR-Fusion input

### ISSUE THREAD

**Issue by immuneAI** [murphycj/AGFusion#38]
I think, recent update from STAR-Fusion, AGFusion batch query not preferring input. Help please

`Traceback (most recent call last):
  File "/software/python/Python-3.5.5/bin/agfusion", line 5, in <module>
    cli.main()
  File "/software/python/Python-3.5.5/lib/python3.5/site-packages/agfusion/cli.py", line 619, in main
    batch_mode(args, agfusion_db, pyensembl_data, rename, colors)
  File "/software/python/Python-3.5.5/lib/python3.5/site-packages/agfusion/cli.py", line 161, in batch_mode
    agfusion_db.logger):
  File "/software/python/Python-3.5.5/lib/python3.5/site-packages/agfusion/parsers.py", line 47, in __init__
    assert line[4] == 'LeftGene', 'Unrecognized STAR-Fusion input'
AssertionError: Unrecognized STAR-Fusion input
`

**Comment by QianhuiXu** [comment]
Hello! I got the same error of STAR-Fusion input file. Did you solved it? 
Any guidance would be much appreciated! Thank you very much!
