### ISSUE TITLE
Issues with agfusion batch: TypeError: save_images() got an unexpected keyword argument 'plot_WT'

### ISSUE THREAD

**Issue by QianhuiXu** [murphycj/AGFusion#44]
Hello,

AGFusion is a wonderful tool！
I ran into an issue with running agfusion batch with my own star-fusion file.

My command:
(agfusion) shpc_100668@shpc44:~$ agfusion batch \
> -f /home/shpc_100668/fusion/star-fusion.fusion_predictions.abridged \
> -a starfusion \
> -db agfusion.homo_sapiens.95.db \
> -o /home/shpc_100668/fusion/starfusion2agfusion/ \
> --middlestar \
> --noncanonical

Error:
2022-11-02 16:06:34,939 - AGFusion - WARNING - Output directory /home/shpc_100668/fusion/starfusion2agfusion/ already exists! Overwriting...
WARNING:AGFusion:Output directory /home/shpc_100668/fusion/starfusion2agfusion/ already exists! Overwriting...
2022-11-02 16:06:34,940 - AGFusion - INFO - Read 12 fusions from the file.
INFO:AGFusion:Read 12 fusions from the file.
INFO:pyensembl.sequence_data:Loaded sequence dictionary from /home/shpc_100668/.cache/pyensembl/GRCh38/ensembl95/Homo_sapiens.GRCh38.cdna.all.fa.gz.pickle
INFO:pyensembl.sequence_data:Loaded sequence dictionary from /home/shpc_100668/.cache/pyensembl/GRCh38/ensembl95/Homo_sapiens.GRCh38.ncrna.fa.gz.pickle
Traceback (most recent call last):
  File "/home/shpc_100668/anaconda3/envs/agfusion/bin/agfusion", line 5, in <module>
    cli.main()
  File "/home/shpc_100668/anaconda3/envs/agfusion/lib/python3.6/site-packages/agfusion/cli.py", line 616, in main
    batch_mode(args, agfusion_db, pyensembl_data, rename, colors)
  File "/home/shpc_100668/anaconda3/envs/agfusion/lib/python3.6/site-packages/agfusion/cli.py", line 171, in batch_mode
    batch_out_dir=args.out,
  File "/home/shpc_100668/anaconda3/envs/agfusion/lib/python3.6/site-packages/agfusion/cli.py", line 140, in annotate
    exclude=args.exclude_domain,
TypeError: save_images() got an unexpected keyword argument 'plot_WT'

I'm really at a loss as to how to proceed, and any guidance would be much appreciated!
Thank you for your kind help!

**Comment by murphycj** [comment]
Hi @QianhuiXu !

Thanks for reporting this error. I was able to reproduce this error with a test dataset I have from starfusion. I'll see to fixing this bug.
